name: 🔍 Commit Message Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  commitlint:
    name: 📝 Check Commit Messages
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: 📝 Validate Commit Messages
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: '.commitlintrc.json'
          failOnWarnings: false